# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

# list any PHP version you want to test against
php:
  # using major version aliases

  # aliased to a recent 5.5.x version
  - 5.5

# omitting "script:" will default to phpunit
# use the $DB env variable to determine the phpunit.xml to use --configuration phpunit_$DB.xml
script: phpunit  --coverage-text

# configure notifications (email, IRC, campfire etc)
